tools:
    php_cpd:
        enabled: true
    php_cs_fixer:
        enabled: true
    php_loc:
        enabled: true
    php_mess_detector:
        enabled: true
        config:
            rulesets: [phpmd.xml]
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
        config:
            checkstyle:
                enabled: true
            verify_php_doc_comments:
                enabled: true
            doc_comment_fixes:
                enabled: true
            use_statement_fixes:
                enabled: true
                remove_unused: true
                preserve_multiple: false
                order_alphabetically: true
    sensiolabs_security_checker:
        enabled: true
